### ISSUE TITLE
請問如何使用 node.js 刪除 xlsx 檔案的 row?

### ISSUE THREAD

**Issue by BeStronger1983** [nodejs-tw/ama#11]
# 目的

我希望可以用 node.js 讀取副檔名為 xlsx 的試算表，並可以刪除指定的 row。
# 使用的工具

我在 Mac 10.11.6 下使用：
node.js 5.8.0
electron 0.36.0
[xlsx 0.8.0](https://www.npmjs.com/package/xlsx)
# 遇到的問題

不知道怎麼刪除指定的 row。
# 嘗試過的解法

目前使用 xlsx 0.8.0，可讀寫 xlsx 檔，
但是它是以 cell 為單位做操作，無法刪除某一個 row。

google、npm、stackoverflow 都有找過有沒有適合的lib，但目前還沒找到。

**Comment by hung-pin** [comment]
可以試試看 node-xlsx 這個套件

**Comment by BeStronger1983** [comment]
後來在以下的連結找到解法。
https://github.com/SheetJS/js-xlsx/issues/352#issuecomment-171977040
