### ISSUE TITLE
Passport到底怎麼連接上mongodb的

### ISSUE THREAD

**Issue by Ean-tzeng** [nodejs-tw/ama#12]
# 目的

<<明確的了解Passport的運作原理>>
# 使用的工具

<<
    codeanywhere線上IDE( Ubuntu 14.04, node.js 5.2.0, express 4.13.4, mongoose );
    mongodlab;

# 操作流程

<<我的USER資料建立在資料庫(mongodb)當中，想要實作一個使用者登入, 寫過基本的PHP，原本想要直接從資料庫當中撈user透過Express-session塞值給session就好，看到node.js有專門的登入驗證模組，想要學習看看>>
# 遇到的問題

<<爬了很多文章，目前認知是要使用Passport-local去做處理，可是我看來看去，沒有任何一個文件或者是程式碼告訴網站要去連接我的資料庫，那網站到底是從哪裡知道要去哪裡抓資料來驗證呢?還是運作原理不用透過資料庫呢??這問題如果太基本到不想回答的話...能不能提供個網址給小弟參考一下 github上有看過了但是沒看到類似的東西>>

**Comment by Ean-tzeng** [comment]
已找到資源
謝謝

**Comment by clonn** [comment]
有事情都可以找 @dca

**Comment by dca** [comment]
QQ 來晚了嗎，

@s30319 `Passport-local` 去跟資料庫檢查資料的細節要自行實作喔！
可以參考 README 的第一段範例程式

``` js
passport.use(new LocalStrategy(
  function(username, password, done) {
    User.findOne({ username: username }, function (err, user) {
      if (err) { return done(err); }
      if (!user) { return done(null, false); }
      if (!user.verifyPassword(password)) { return done(null, false); }
      return done(null, user);
    });
  }
));
```

取自： https://github.com/jaredhanson/passport-local

**Comment by Ean-tzeng** [comment]
謝謝樓上兩位大大
如果後面在學習上有什麼不懂的
可能還會再來麻煩你們，當然，我自己會先上網做功課
