### ISSUE TITLE
第一次接觸的爬蟲問題

### ISSUE THREAD

**Issue by MissterHao** [nodejs-tw/ama#7]
# 目的

我最近(前兩天)就在期末考中突然想要學nodeJS
所以考完後我就開始嘗試自學了
由於我在自學時很容易出現卡住的地方
所以會有很多基本的問題希望大家能幫我解答

因為是突然想要自學所以我不知道要重哪裡著手
所以我就想說我乾脆來爬一下PTT八卦板上面文章的標題好了
# 使用的工具

我是直接在nodejs的官網上面載最新的msi檔安裝的
# 操作流程

https://gist.github.com/Henry0526/7d556b856a9d9323c4d545cc32a0d5d2

這是我嘗試的code
直接用node GOSSIPING.js執行
# 遇到的問題

但是我爬下來卻出現一堆看不懂的格式
例如:

https://gist.github.com/anonymous/a94109ce2111e1b5b2dd48c51e708dcf

裡面就是我爬下來的樣子
我不懂為什麼會是這個格式耶
# 嘗試過的解法

另外我有試過把var title = $('.title');
改成var title = $('.title').html();
因為我有看過有一個範例網頁這樣寫
但是我不懂為什麼
而且我改了這行的話輸出會變成undefine
希望大家可以幫我指點迷津一下

此外還有
我在學的時候發現好像cheerio這個模組是專門為了Jquery所做的
但是卻不能用下面這類型的方式去尋找Tag

var $ = cheerio.load(body);
var title = $('.title:first');

這種:first的方式去找
也想請教大家這是為什麼?
先謝謝大家了!!

**Comment by fillano** [comment]
你去cheerio官網看一下啦。基本上，他只是「實作」了jQuery核心的功能，但應該不是全部。

另外，他回傳的看起來是一個DOM物件的List（不是Array，但是可以用數字索引操作）。

晧暐 notifications@github.com 於 2016年6月24日 下午10:13 寫道：

> 目的
> 
> 我最近(前兩天)就在期末考中突然想要學nodeJS
> 所以考完後我就開始嘗試自學了
> 由於我在自學時很容易出現卡住的地方
> 所以會有很多基本的問題希望大家能幫我解答
> 
> 因為是突然想要自學所以我不知道要重哪裡著手
> 所以我就想說我乾脆來爬一下八卦板上面文章的標題好了
> 使用的工具
> 
> 我是直接在nodejs的官網上面載最新的msi檔安裝的
> 操作流程
> 
> https://gist.github.com/Henry0526/7d556b856a9d9323c4d545cc32a0d5d2
> 
> 這是我嘗試的code
> 直接用node GOSSIPING.js執行
> 遇到的問題
> 
> 但是我爬下來卻出現一堆看不懂的格式
> 例如:
> 
> https://gist.github.com/anonymous/a94109ce2111e1b5b2dd48c51e708dcf
> 
> 裡面就是我爬下來的樣子
> 我不懂為什麼會是這個格式耶
> 嘗試過的解法
> 
> 另外我有試過把var title = $('.title');
> 改成var title = $('.title').html();
> 因為我有看過有一個範例網頁這樣寫
> 但是我不懂為什麼
> 而且我改了這行的話輸出會變成undefine
> 希望大家可以幫我指點迷津一下
> 
> 此外還有
> 我在學的時候發現好像cheerio這個模組是專門為了Jquery所做的
> 但是卻不能用下面這類型的方式去尋找Tag
> 
> var $ = cheerio.load(body);
> var title = $('.title:first');
> 
> 這種:first的方式去找
> 也想請教大家這是為什麼?
> 先謝謝大家了!!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nodejs-tw/ama/issues/7, or mute the thread
> https://github.com/notifications/unsubscribe/AAFSO14u4tY-89ALeJ44hnEF9vm0RWwEks5qO-XygaJpZM4I9zmi
> .

## 

AUFKLÄRUNG ist der Ausgang des Menschen aus seiner selbstverschuldeten
Unmündigkeit. Unmündigkeit ist das Unvermögen, sich seines Verstandes ohne
Leitung eines anderen zu bedienen. Selbstverschuldet ist diese
Unmündigkeit, wenn die Ursache derselben nicht am Mangel des Verstandes,
sondern der Entschließung und des Mutes liegt, sich seiner ohne Leitung
eines andern zu bedienen. Sapere aude! Habe Mut, dich deines eigenen
Verstandes zu bedienen! ist also der Wahlspruch der Aufklärung.

**Comment by LinZap** [comment]
```js
var title = $('.title:first');
```
改一下，下面這個寫法就是你要的

```js
var titles = $('.title'),
      title = $(titles[0])
```

:man_cook:
